// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deleteFeedByURLandUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedRecord = `-- name: DeleteFeedRecord :exec
DELETE FROM feed_follows
WHERE user_id = $1 and feed_id = $2
`

type DeleteFeedRecordParams struct {
	UserID uuid.UUID
	FeedID int64
}

func (q *Queries) DeleteFeedRecord(ctx context.Context, arg DeleteFeedRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedRecord, arg.UserID, arg.FeedID)
	return err
}
